#ifndef KASUMI_RERANKING_VERSION_H
#define KASUMI_RERANKING_VERSION_H

#define KASUMI_RERANKING_VERSION "0.1.0"
#define KASUMI_RERANKING_VERSION_MAJOR 0
#define KASUMI_RERANKING_VERSION_MINOR 1
#define KASUMI_RERANKING_VERSION_PATCH 0

#endif // KASUMI_RERANKING_VERSION_H
