// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kasumi/v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionContext provides the environment and ephemeral state for a given event.
// Under APPI compliance, the user_id / session_id must not be logged directly;
// they should be hashed at the edge before long-term persistence or aggregation.
type SessionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Optional, often empty for anonymous users
	DeviceType    string                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	GeoRegion     string                 `protobuf:"bytes,4,opt,name=geo_region,json=geoRegion,proto3" json:"geo_region,omitempty"` // High-level region for latency routing / broad popularity
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionContext) Reset() {
	*x = SessionContext{}
	mi := &file_kasumi_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContext) ProtoMessage() {}

func (x *SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_kasumi_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContext.ProtoReflect.Descriptor instead.
func (*SessionContext) Descriptor() ([]byte, []int) {
	return file_kasumi_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *SessionContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionContext) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *SessionContext) GetGeoRegion() string {
	if x != nil {
		return x.GeoRegion
	}
	return ""
}

func (x *SessionContext) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ClickEvent is emitted when a user clicks on an item.
type ClickEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Context         *SessionContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ItemId          string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	SourcePlacement string                 `protobuf:"bytes,3,opt,name=source_placement,json=sourcePlacement,proto3" json:"source_placement,omitempty"` // e.g., "homepage_feed", "search_results"
	RankPosition    int32                  `protobuf:"varint,4,opt,name=rank_position,json=rankPosition,proto3" json:"rank_position,omitempty"`         // Position in the list where the item was shown
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	mi := &file_kasumi_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kasumi_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_kasumi_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *ClickEvent) GetContext() *SessionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ClickEvent) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ClickEvent) GetSourcePlacement() string {
	if x != nil {
		return x.SourcePlacement
	}
	return ""
}

func (x *ClickEvent) GetRankPosition() int32 {
	if x != nil {
		return x.RankPosition
	}
	return 0
}

// DwellEvent is emitted when a user views an item for a significant duration.
type DwellEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *SessionContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	DurationMs    int32                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DwellEvent) Reset() {
	*x = DwellEvent{}
	mi := &file_kasumi_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DwellEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DwellEvent) ProtoMessage() {}

func (x *DwellEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kasumi_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DwellEvent.ProtoReflect.Descriptor instead.
func (*DwellEvent) Descriptor() ([]byte, []int) {
	return file_kasumi_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *DwellEvent) GetContext() *SessionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DwellEvent) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DwellEvent) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// RecommendationRequest asks for a personalized ranked list of items.
type RecommendationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Context          *SessionContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	NumCandidates    int32                  `protobuf:"varint,2,opt,name=num_candidates,json=numCandidates,proto3" json:"num_candidates,omitempty"`         // How many final candidates to return (e.g., 20)
	FilterCategories []string               `protobuf:"bytes,3,rep,name=filter_categories,json=filterCategories,proto3" json:"filter_categories,omitempty"` // Optional category filters
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecommendationRequest) Reset() {
	*x = RecommendationRequest{}
	mi := &file_kasumi_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationRequest) ProtoMessage() {}

func (x *RecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kasumi_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationRequest.ProtoReflect.Descriptor instead.
func (*RecommendationRequest) Descriptor() ([]byte, []int) {
	return file_kasumi_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendationRequest) GetContext() *SessionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RecommendationRequest) GetNumCandidates() int32 {
	if x != nil {
		return x.NumCandidates
	}
	return 0
}

func (x *RecommendationRequest) GetFilterCategories() []string {
	if x != nil {
		return x.FilterCategories
	}
	return nil
}

// ScoredItem is a single ranked candidate.
type ScoredItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemId         string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Score          float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	FallbackReason string                 `protobuf:"bytes,3,opt,name=fallback_reason,json=fallbackReason,proto3" json:"fallback_reason,omitempty"` // Populated if reranking failed and fallback was used
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScoredItem) Reset() {
	*x = ScoredItem{}
	mi := &file_kasumi_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredItem) ProtoMessage() {}

func (x *ScoredItem) ProtoReflect() protoreflect.Message {
	mi := &file_kasumi_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredItem.ProtoReflect.Descriptor instead.
func (*ScoredItem) Descriptor() ([]byte, []int) {
	return file_kasumi_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *ScoredItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ScoredItem) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoredItem) GetFallbackReason() string {
	if x != nil {
		return x.FallbackReason
	}
	return ""
}

// RecommendationResponse contains the final ordered candidates.
type RecommendationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Items            []*ScoredItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	RecommendationId string                 `protobuf:"bytes,2,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"` // Tracing ID for joining with subsequent clicks
	LatencyMs        int32                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`                     // Total server-side latency for observation
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecommendationResponse) Reset() {
	*x = RecommendationResponse{}
	mi := &file_kasumi_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationResponse) ProtoMessage() {}

func (x *RecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kasumi_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationResponse.ProtoReflect.Descriptor instead.
func (*RecommendationResponse) Descriptor() ([]byte, []int) {
	return file_kasumi_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *RecommendationResponse) GetItems() []*ScoredItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RecommendationResponse) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *RecommendationResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// StreamEventWrapper wraps either a click or a dwell for multiplexed streaming.
type StreamEventWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamEventWrapper_Click
	//	*StreamEventWrapper_Dwell
	Event         isStreamEventWrapper_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventWrapper) Reset() {
	*x = StreamEventWrapper{}
	mi := &file_kasumi_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventWrapper) ProtoMessage() {}

func (x *StreamEventWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_kasumi_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventWrapper.ProtoReflect.Descriptor instead.
func (*StreamEventWrapper) Descriptor() ([]byte, []int) {
	return file_kasumi_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *StreamEventWrapper) GetEvent() isStreamEventWrapper_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamEventWrapper) GetClick() *ClickEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamEventWrapper_Click); ok {
			return x.Click
		}
	}
	return nil
}

func (x *StreamEventWrapper) GetDwell() *DwellEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamEventWrapper_Dwell); ok {
			return x.Dwell
		}
	}
	return nil
}

type isStreamEventWrapper_Event interface {
	isStreamEventWrapper_Event()
}

type StreamEventWrapper_Click struct {
	Click *ClickEvent `protobuf:"bytes,1,opt,name=click,proto3,oneof"`
}

type StreamEventWrapper_Dwell struct {
	Dwell *DwellEvent `protobuf:"bytes,2,opt,name=dwell,proto3,oneof"`
}

func (*StreamEventWrapper_Click) isStreamEventWrapper_Event() {}

func (*StreamEventWrapper_Dwell) isStreamEventWrapper_Event() {}

// IngestionResponse is returned after successful ingestion.
type IngestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionResponse) Reset() {
	*x = IngestionResponse{}
	mi := &file_kasumi_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionResponse) ProtoMessage() {}

func (x *IngestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kasumi_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionResponse.ProtoReflect.Descriptor instead.
func (*IngestionResponse) Descriptor() ([]byte, []int) {
	return file_kasumi_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *IngestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_kasumi_v1_events_proto protoreflect.FileDescriptor

const file_kasumi_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x16kasumi/v1/events.proto\x12\tkasumi.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n" +
	"\x0eSessionContext\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x1d\n" +
	"\n" +
	"geo_region\x18\x04 \x01(\tR\tgeoRegion\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xaa\x01\n" +
	"\n" +
	"ClickEvent\x123\n" +
	"\acontext\x18\x01 \x01(\v2\x19.kasumi.v1.SessionContextR\acontext\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12)\n" +
	"\x10source_placement\x18\x03 \x01(\tR\x0fsourcePlacement\x12#\n" +
	"\rrank_position\x18\x04 \x01(\x05R\frankPosition\"{\n" +
	"\n" +
	"DwellEvent\x123\n" +
	"\acontext\x18\x01 \x01(\v2\x19.kasumi.v1.SessionContextR\acontext\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x05R\n" +
	"durationMs\"\xa0\x01\n" +
	"\x15RecommendationRequest\x123\n" +
	"\acontext\x18\x01 \x01(\v2\x19.kasumi.v1.SessionContextR\acontext\x12%\n" +
	"\x0enum_candidates\x18\x02 \x01(\x05R\rnumCandidates\x12+\n" +
	"\x11filter_categories\x18\x03 \x03(\tR\x10filterCategories\"d\n" +
	"\n" +
	"ScoredItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12'\n" +
	"\x0ffallback_reason\x18\x03 \x01(\tR\x0efallbackReason\"\x91\x01\n" +
	"\x16RecommendationResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.kasumi.v1.ScoredItemR\x05items\x12+\n" +
	"\x11recommendation_id\x18\x02 \x01(\tR\x10recommendationId\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x05R\tlatencyMs\"{\n" +
	"\x12StreamEventWrapper\x12-\n" +
	"\x05click\x18\x01 \x01(\v2\x15.kasumi.v1.ClickEventH\x00R\x05click\x12-\n" +
	"\x05dwell\x18\x02 \x01(\v2\x15.kasumi.v1.DwellEventH\x00R\x05dwellB\a\n" +
	"\x05event\"G\n" +
	"\x11IngestionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe9\x01\n" +
	"\x10IngestionService\x12B\n" +
	"\vIngestClick\x12\x15.kasumi.v1.ClickEvent\x1a\x1c.kasumi.v1.IngestionResponse\x12B\n" +
	"\vIngestDwell\x12\x15.kasumi.v1.DwellEvent\x1a\x1c.kasumi.v1.IngestionResponse\x12M\n" +
	"\fStreamEvents\x12\x1d.kasumi.v1.StreamEventWrapper\x1a\x1c.kasumi.v1.IngestionResponse(\x012r\n" +
	"\x15RecommendationService\x12Y\n" +
	"\x12GetRecommendations\x12 .kasumi.v1.RecommendationRequest\x1a!.kasumi.v1.RecommendationResponseB2Z0github.com/kasumi-engine/ingestion/api/kasumi/v1b\x06proto3"

var (
	file_kasumi_v1_events_proto_rawDescOnce sync.Once
	file_kasumi_v1_events_proto_rawDescData []byte
)

func file_kasumi_v1_events_proto_rawDescGZIP() []byte {
	file_kasumi_v1_events_proto_rawDescOnce.Do(func() {
		file_kasumi_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kasumi_v1_events_proto_rawDesc), len(file_kasumi_v1_events_proto_rawDesc)))
	})
	return file_kasumi_v1_events_proto_rawDescData
}

var file_kasumi_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kasumi_v1_events_proto_goTypes = []any{
	(*SessionContext)(nil),         // 0: kasumi.v1.SessionContext
	(*ClickEvent)(nil),             // 1: kasumi.v1.ClickEvent
	(*DwellEvent)(nil),             // 2: kasumi.v1.DwellEvent
	(*RecommendationRequest)(nil),  // 3: kasumi.v1.RecommendationRequest
	(*ScoredItem)(nil),             // 4: kasumi.v1.ScoredItem
	(*RecommendationResponse)(nil), // 5: kasumi.v1.RecommendationResponse
	(*StreamEventWrapper)(nil),     // 6: kasumi.v1.StreamEventWrapper
	(*IngestionResponse)(nil),      // 7: kasumi.v1.IngestionResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_kasumi_v1_events_proto_depIdxs = []int32{
	8,  // 0: kasumi.v1.SessionContext.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: kasumi.v1.ClickEvent.context:type_name -> kasumi.v1.SessionContext
	0,  // 2: kasumi.v1.DwellEvent.context:type_name -> kasumi.v1.SessionContext
	0,  // 3: kasumi.v1.RecommendationRequest.context:type_name -> kasumi.v1.SessionContext
	4,  // 4: kasumi.v1.RecommendationResponse.items:type_name -> kasumi.v1.ScoredItem
	1,  // 5: kasumi.v1.StreamEventWrapper.click:type_name -> kasumi.v1.ClickEvent
	2,  // 6: kasumi.v1.StreamEventWrapper.dwell:type_name -> kasumi.v1.DwellEvent
	1,  // 7: kasumi.v1.IngestionService.IngestClick:input_type -> kasumi.v1.ClickEvent
	2,  // 8: kasumi.v1.IngestionService.IngestDwell:input_type -> kasumi.v1.DwellEvent
	6,  // 9: kasumi.v1.IngestionService.StreamEvents:input_type -> kasumi.v1.StreamEventWrapper
	3,  // 10: kasumi.v1.RecommendationService.GetRecommendations:input_type -> kasumi.v1.RecommendationRequest
	7,  // 11: kasumi.v1.IngestionService.IngestClick:output_type -> kasumi.v1.IngestionResponse
	7,  // 12: kasumi.v1.IngestionService.IngestDwell:output_type -> kasumi.v1.IngestionResponse
	7,  // 13: kasumi.v1.IngestionService.StreamEvents:output_type -> kasumi.v1.IngestionResponse
	5,  // 14: kasumi.v1.RecommendationService.GetRecommendations:output_type -> kasumi.v1.RecommendationResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_kasumi_v1_events_proto_init() }
func file_kasumi_v1_events_proto_init() {
	if File_kasumi_v1_events_proto != nil {
		return
	}
	file_kasumi_v1_events_proto_msgTypes[6].OneofWrappers = []any{
		(*StreamEventWrapper_Click)(nil),
		(*StreamEventWrapper_Dwell)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kasumi_v1_events_proto_rawDesc), len(file_kasumi_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kasumi_v1_events_proto_goTypes,
		DependencyIndexes: file_kasumi_v1_events_proto_depIdxs,
		MessageInfos:      file_kasumi_v1_events_proto_msgTypes,
	}.Build()
	File_kasumi_v1_events_proto = out.File
	file_kasumi_v1_events_proto_goTypes = nil
	file_kasumi_v1_events_proto_depIdxs = nil
}
