"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SessionContext(_message.Message):
    """---------------------------------------------------------
    Event Intake
    ---------------------------------------------------------

    SessionContext provides the environment and ephemeral state for a given event.
    Under APPI compliance, the user_id / session_id must not be logged directly;
    they should be hashed at the edge before long-term persistence or aggregation.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    DEVICE_TYPE_FIELD_NUMBER: _builtins.int
    GEO_REGION_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    user_id: _builtins.str
    """Optional, often empty for anonymous users"""
    device_type: _builtins.str
    geo_region: _builtins.str
    """High-level region for latency routing / broad popularity"""
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        user_id: _builtins.str = ...,
        device_type: _builtins.str = ...,
        geo_region: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_type", b"device_type", "geo_region", b"geo_region", "session_id", b"session_id", "timestamp", b"timestamp", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionContext: _TypeAlias = SessionContext  # noqa: Y015

@_typing.final
class ClickEvent(_message.Message):
    """ClickEvent is emitted when a user clicks on an item."""

    DESCRIPTOR: _descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: _builtins.int
    ITEM_ID_FIELD_NUMBER: _builtins.int
    SOURCE_PLACEMENT_FIELD_NUMBER: _builtins.int
    RANK_POSITION_FIELD_NUMBER: _builtins.int
    item_id: _builtins.str
    source_placement: _builtins.str
    """e.g., "homepage_feed", "search_results" """
    rank_position: _builtins.int
    """Position in the list where the item was shown"""
    @_builtins.property
    def context(self) -> Global___SessionContext: ...
    def __init__(
        self,
        *,
        context: Global___SessionContext | None = ...,
        item_id: _builtins.str = ...,
        source_placement: _builtins.str = ...,
        rank_position: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "item_id", b"item_id", "rank_position", b"rank_position", "source_placement", b"source_placement"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClickEvent: _TypeAlias = ClickEvent  # noqa: Y015

@_typing.final
class DwellEvent(_message.Message):
    """DwellEvent is emitted when a user views an item for a significant duration."""

    DESCRIPTOR: _descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: _builtins.int
    ITEM_ID_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    item_id: _builtins.str
    duration_ms: _builtins.int
    @_builtins.property
    def context(self) -> Global___SessionContext: ...
    def __init__(
        self,
        *,
        context: Global___SessionContext | None = ...,
        item_id: _builtins.str = ...,
        duration_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "duration_ms", b"duration_ms", "item_id", b"item_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DwellEvent: _TypeAlias = DwellEvent  # noqa: Y015

@_typing.final
class RecommendationRequest(_message.Message):
    """---------------------------------------------------------
    Recommendation
    ---------------------------------------------------------

    RecommendationRequest asks for a personalized ranked list of items.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: _builtins.int
    NUM_CANDIDATES_FIELD_NUMBER: _builtins.int
    FILTER_CATEGORIES_FIELD_NUMBER: _builtins.int
    num_candidates: _builtins.int
    """How many final candidates to return (e.g., 20)"""
    @_builtins.property
    def context(self) -> Global___SessionContext: ...
    @_builtins.property
    def filter_categories(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Optional category filters"""

    def __init__(
        self,
        *,
        context: Global___SessionContext | None = ...,
        num_candidates: _builtins.int = ...,
        filter_categories: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "filter_categories", b"filter_categories", "num_candidates", b"num_candidates"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RecommendationRequest: _TypeAlias = RecommendationRequest  # noqa: Y015

@_typing.final
class ScoredItem(_message.Message):
    """ScoredItem is a single ranked candidate."""

    DESCRIPTOR: _descriptor.Descriptor

    ITEM_ID_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    FALLBACK_REASON_FIELD_NUMBER: _builtins.int
    item_id: _builtins.str
    score: _builtins.float
    fallback_reason: _builtins.str
    """Populated if reranking failed and fallback was used"""
    def __init__(
        self,
        *,
        item_id: _builtins.str = ...,
        score: _builtins.float = ...,
        fallback_reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fallback_reason", b"fallback_reason", "item_id", b"item_id", "score", b"score"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScoredItem: _TypeAlias = ScoredItem  # noqa: Y015

@_typing.final
class RecommendationResponse(_message.Message):
    """RecommendationResponse contains the final ordered candidates."""

    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    RECOMMENDATION_ID_FIELD_NUMBER: _builtins.int
    LATENCY_MS_FIELD_NUMBER: _builtins.int
    recommendation_id: _builtins.str
    """Tracing ID for joining with subsequent clicks"""
    latency_ms: _builtins.int
    """Total server-side latency for observation"""
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScoredItem]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[Global___ScoredItem] | None = ...,
        recommendation_id: _builtins.str = ...,
        latency_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items", "latency_ms", b"latency_ms", "recommendation_id", b"recommendation_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RecommendationResponse: _TypeAlias = RecommendationResponse  # noqa: Y015

@_typing.final
class StreamEventWrapper(_message.Message):
    """StreamEventWrapper wraps either a click or a dwell for multiplexed streaming."""

    DESCRIPTOR: _descriptor.Descriptor

    CLICK_FIELD_NUMBER: _builtins.int
    DWELL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def click(self) -> Global___ClickEvent: ...
    @_builtins.property
    def dwell(self) -> Global___DwellEvent: ...
    def __init__(
        self,
        *,
        click: Global___ClickEvent | None = ...,
        dwell: Global___DwellEvent | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["click", b"click", "dwell", b"dwell", "event", b"event"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["click", b"click", "dwell", b"dwell", "event", b"event"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["click", "dwell"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___StreamEventWrapper: _TypeAlias = StreamEventWrapper  # noqa: Y015

@_typing.final
class IngestionResponse(_message.Message):
    """IngestionResponse is returned after successful ingestion."""

    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    message: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___IngestionResponse: _TypeAlias = IngestionResponse  # noqa: Y015
